name: Docker Build & Push (Frontend)

on:
  workflow_run:
    workflows: ["Build & Test React CI"]
    types:
      - completed
  push:
    branches: [main]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    if: >
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') ||
      (github.event_name == 'push')

    steps:
      # ---- Checkout repo ----
      - name: Checkout repository
        uses: actions/checkout@v4

      # ---- Docker login ----
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # ---- Build Docker image ----
      - name: Build Docker image
        run: |
          docker build \
            -t ${{ secrets.DOCKER_USERNAME }}/myesi-frontend:${{ github.sha }} \
            -t ${{ secrets.DOCKER_USERNAME }}/myesi-frontend:latest .

      # ---- Push images ----
      - name: Push Docker images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/myesi-frontend:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/myesi-frontend:latest